#!/bin/bash
#==============================================================================
# Copyright (C) 2007-2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

install_driver() {
    local install_logfile
    if [ -x "${cw_NVIDIA_DRIVER_installer}" ]; then
        install_logfile="$(dirname "${cw_NVIDIA_DRIVER_log}")"/nvidia-driver-install-$(date +"%Y%m%d-%H%M%S").log
        log "Installing nvidia driver (installation log: ${install_logfile})" "${cw_NVIDIA_DRIVER_log}"
        if ! "${cw_NVIDIA_DRIVER_installer}" --kernel-name=$(uname -r) \
            --no-network --silent --disable-nouveau \
            --log-file-name="${install_logfile}"; then
            log "Driver installation failed" "${cw_NVIDIA_DRIVER_log}"
            return 1
        fi
    else
        log "Could not find installer: ${cw_NVIDIA_DRIVER_installer}" "${cw_NVIDIA_DRIVER_log}"
        return 1
    fi
}

main() {
    local nvdevs n3d nvga n i
    set -o pipefail
    log "Checking for existence of nvidia driver" "${cw_NVIDIA_DRIVER_log}"
    if ! /sbin/modinfo nvidia 2>&1 | log_blob "${cw_NVIDIA_DRIVER_log}" "modinfo"; then
        log "Driver not found - executing installer" "${cw_NVIDIA_DRIVER_log}"
        install_driver || return 1
    fi
    log "Loading nvidia driver" "${cw_NVIDIA_DRIVER_log}"
    if /sbin/modprobe nvidia 2>&1 | log_blob "${cw_NVIDIA_DRIVER_log}" "modprobe"; then
        # Count the number of NVIDIA controllers found.
        nvdevs=$(lspci | grep -i NVIDIA)
        n3d=$(echo "$nvdevs" | grep "3D controller" | wc -l)
        nvga=$(echo "$nvdevs" | grep "VGA compatible controller" | wc -l)

        n=$(($n3d+$nvga-1))
        for i in $(seq 0 $n); do
            if [ -c /dev/nvidia$i ]; then
                log "Already exists: /dev/nvidia$i" "${cw_NVIDIA_DRIVER_log}"
            elif ! mknod -m 666 /dev/nvidia$i c 195 $i; then
                log "Failed to create /dev/nvidia$i" "${cw_NVIDIA_DRIVER_log}"
            else
                log "Created /dev/nvidia$i" "${cw_NVIDIA_DRIVER_log}"
            fi
        done
        if [ -c /dev/nvidiactl ]; then
            log "Already exists: /dev/nvidiactl" "${cw_NVIDIA_DRIVER_log}"
        elif  ! mknod -m 666 /dev/nvidiactl c 195 255; then
            log "Failed to create /dev/nvidiactl" "${cw_NVIDIA_DRIVER_log}"
        else
            log "Created /dev/nvidiactl" "${cw_NVIDIA_DRIVER_log}"
        fi
    else
        log "Unable to load nvidia driver" "${cw_NVIDIA_DRIVER_log}"
    fi
}

setup
require log
if [ -f "${cw_ROOT}/etc/nvidia-driver.vars.sh" ]; then
    . "${cw_ROOT}/etc/nvidia-driver.vars.sh"
    tee >(main "$@")
fi
