#!/bin/bash
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local a depots depot_meta depot_id depot_name

    . ${cw_ROOT}/etc/config/cluster/instance.vars.sh
    cw_INSTANCE_log=${cw_INSTANCE_log:-/var/log/clusterware/instance.log}
    if [ "${cw_INSTANCE_role}" == "slave" ]; then
        payload=($(cat))
        log "Received payload from master: ${payload[*]}" "${cw_INSTANCE_log}"
        depots="${payload[@]:1}"
        for a in $depots; do
            IFS=':' read -a depot_meta <<< "${a}"
            depot_id="${depot_meta[0]}"
            depot_name="${depot_meta[1]}"
            log "Found depot: id: ${depot_id}, name: ${depot_name}" "${cw_INSTANCE_log}"
            mkdir -p "/opt/gridware/depots/${depot_id}"
            if [ "${depot_name}" == "local" ]; then
                log "Updating local repository configuration to use ${depot_id}" "${cw_INSTANCE_log}"
                source="$(readlink /opt/gridware/local)"
                target="/opt/gridware/depots/${depot_id}"
                sed -e 's,${source},${target},g' -i "${cw_ROOT}/etc/packager.yml"
            fi
            ln -snf "/opt/gridware/depots/${depot_id}" "/opt/gridware/${depot_name}"
        done
    fi
}

setup
require log
require handler

handler_tee main "$@"
