#!/bin/bash
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local depots depot_name depot_id
    . ${cw_ROOT}/etc/config/cluster/instance.vars.sh
    if [ "${cw_INSTANCE_role}" == "master" ]; then
        depots=()
        for a in /opt/gridware/*; do
            if [ -L "$a" ]; then
                depot_name=$(basename $a)
                depot_id=$(basename $(readlink $a))
                depots+=(${depot_id}:${depot_name})
            fi
        done
        if [ "${depots}" ]; then
            handler_broadcast depots-available ${depots[*]}
        fi
    fi
}

setup
require handler

handler_tee main "$@"
