#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler support script
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################

. /etc/profile.d/alces-clusterware.sh
. /etc/xdg/clusterware/config.vars.sh
module purge
module use "${cw_ROOT}"/etc/modules
module load services/slurm

_lock() {
    mkdir -p "${cw_ROOT}"/var/lock
    exec 9> "${cw_ROOT}"/var/lock/cluster-slurm.lock && flock -w30 9
}

_unlock() {
    exec 9>&-
}


hostname="$(echo "$1" | cut -f1 -d.)"
group="$2"


if _lock; then
  nodeline=$(scontrol show PartitionName="$group" | grep -e " Nodes=.*" | sed -e "s/Nodes=\(.*\)/Nodes=$hostname,\1/" -e "s/,(null)//")
  scontrol update PartitionName="$group" ${nodeline}
fi
_unlock
