#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler support script
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################

. /etc/profile.d/alces-clusterware.sh
. /etc/xdg/clusterware/config.vars.sh
module purge
module use "${cw_ROOT}"/etc/modules
module load services/slurm

. $(dirname ${BASH_SOURCE[-1]})/common

hostname="$(echo "$1" | cut -f1 -d.)"
group="$2"


if _lock; then
  nodeline=$(scontrol show PartitionName="$group" | grep -e " Nodes=.*" | sed -e "s/Nodes=\(.*\)/Nodes=$hostname,\1/" -e "s/,(null)//")
  echo "[debug] About to run: scontrol update PartitionName=\"$group\" ${nodeline}"
  scontrol update PartitionName="$group" ${nodeline}
  _rewrite_config
  _unlock
else
  echo "Could not obtain lock; can't update partition"
fi
