#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler support script
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################

. /etc/profile.d/alces-clusterware.sh
. /etc/xdg/clusterware/config.vars.sh
module purge
module use "${cw_ROOT}"/etc/modules
module load services/slurm

_lock() {
    mkdir -p "${cw_ROOT}"/var/lock
    exec 9> "${cw_ROOT}"/var/lock/cluster-slurm.lock && flock -w30 9
}

_unlock() {
    exec 9>&-
}


name="$1"
maxsize="$2"


if ! sinfo -o "%R" -a | grep "$name"; then
  if _lock; then
    scontrol create PartitionName="$name"
  fi
_unlock

fi
