#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler support script
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################

. $(dirname ${BASH_SOURCE[-1]})/common

name="$1"
maxsize="$2"


if ! sinfo -o "%R" -a | grep "$name"; then
  if _lock; then
    echo "Creating new partition $name"
    # Slurm docs lie; we need a trailing comma after empty nodelist for it to be valid
    echo "PartitionName=$name Nodes=," >> "${cw_CLUSTER_SLURM_config}"
    _unlock
  else
    echo "Could not obtain lock; can't add partition"
  fi
fi
