#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler support functions
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################

_lock() {
    mkdir -p "${cw_ROOT}"/var/lock
    exec 9> "${cw_ROOT}"/var/lock/cluster-slurm.lock && flock -w30 9
}

_unlock() {
    exec 9>&-
}

_rewrite_config() {
  # Other parts of processing directly modify the Slurm config file and trigger
  # a reload of slurmctld. In order that our changes here not be overwritten,
  # we ask Slurm to write a copy of its (in-memory) config and then use that to
  # overwrite the on-disk config file.
  local tempconfig
  tempconfig=$(scontrol write config | cut -f5 -d' ')
  cat "$tempconfig" | sed -e "/CpuFreqDef=Unknown/d" > "${cw_CLUSTER_SLURM_config}"
}
