#!/bin/bash
alces_ROOT="/opt/clusterware"

source "${alces_ROOT}/etc/config/instance/task.vars.sh"
# Re-execute ourselves as the RUNUSER before starting the session.
if [ "$UID" != "$(id -u $RUNUSER)" ]; then
   exec su $RUNUSER -c "${BASH_SOURCE[0]}" "$@"
fi

PATH="${alces_ROOT}/bin:${PATH}"
SESSION=${SESSION-:default}

sessionid=$(alces session start --terse $SESSION)
alces session wait $sessionid 1>&2
