#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2015-2016 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

_update_ssh_shosts() {
    local ip
    ip="$1"
    echo "Adding IP address to shosts: $ip"
    echo "${ip}" >> /root/.shosts
}

_update_ssh_known_hosts() {
    local ip
    ip="$1"
    echo "Adding SSH host keys for: $ip"
    ssh-keyscan "$(getent hosts ${ip} | tr -s ' ' ',')" >> /etc/ssh/ssh_known_hosts
}

main() {
    local count member_data
    member_data="$(cat)"
    member_register <<< "${member_data}"
    count="$(member_count)"
    if [ "${count}" -ge "$(member_quorum)" ]; then
        handler_run_hook cluster-quorate "${count}"
    fi

    eval $(member_parse <<< "${member_data}")
    instance_id=$(member_find_tag aws_instanceid "${cw_MEMBER_tags}")
    if [ "${instance_id}" ]; then
        machine_type=$(member_find_tag aws_machinetype "${cw_MEMBER_tags}")
        "${cw_ROOT}"/libexec/share/flight-recorder "join" "${instance_id}" "${cw_MEMBER_role}" "${machine_type}"
    fi

    "${cw_ROOT}"/libexec/share/update-etc-hosts "${cw_MEMBER_name}" "${cw_MEMBER_ip}"
    if [ "${cw_MEMBER_role}" == "master" ]; then
        _update_ssh_shosts "${cw_MEMBER_ip}"
    fi

    _update_ssh_known_hosts "${cw_MEMBER_ip}" "${cw_MEMBER_name}"

    files_load_config instance config/cluster
    if [[ "${cw_INSTANCE_role}" == "master" ]]; then
        storage_broadcast_enabled
        storage_sync_to_slaves "${cw_MEMBER_ip}"
        storage_sync_to_slaves --default "${cw_MEMBER_ip}"
    fi
}

setup

require member
require handler
require files
require storage

handler_tee main "$@"
