#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

_member_purge() {
    type member_purge &>/dev/null && member_purge
}

_setup_aws() {
    if [ -f /sys/hypervisor/uuid -a "$(head -c3 /sys/hypervisor/uuid)" == "ec2" ]; then
        eval $(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | \
                 ${_JQ} -r \
                 '"region=\(.region)"','"ctime=\(.pendingTime)"','"instanceid=\(.instanceId)"')
        cat <<EOF > "${cw_ROOT}"/etc/config/cluster/instance-aws.rc
cw_INSTANCE_aws_region="${region}"
cw_INSTANCE_aws_ctime="${ctime}"
cw_INSTANCE_aws_instanceid="${instanceid}"
EOF
    elif [ "$cw_TEST_mock_aws" ]; then
        cat <<EOF > "${cw_ROOT}"/etc/config/cluster/instance-aws.rc
cw_INSTANCE_aws_region="eu-west-1"
cw_INSTANCE_aws_ctime="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cw_INSTANCE_aws_instanceid="i-$(hostname | md5sum | cut -c1-8)"
EOF
    fi
}

main() {
    # Purge any known existing members in advance of rejoining the
    # cluster service ring.
    _member_purge

    # Bail out if we're already configured (this is a reboot)
    if [ -d "${cw_ROOT}/etc/config/cluster" ]; then
        exit 0
    fi

    # Bail out if we can't locate the config file
    if [ ! -f "${cw_ROOT}/etc/config.yml" ]; then
        exit 1
    fi

    # Parse YAML file into something useful
    mkdir -p "${cw_ROOT}/etc/config/cluster/serf"
    _setup_aws

    ruby_run <<RUBY
require 'yaml'
require 'json'

def write_file(name, content, *args)
  File.write("${cw_ROOT}/etc/config/cluster/#{name}",content,*args)
end

config = YAML.load_file('${cw_ROOT}/etc/config.yml')['cluster']

if config['master']
  h = { retry_join: [config['master']] }
  write_file('serf/join.json', h.to_json)
end

h = { discover: config['uuid'] }
write_file('serf/cluster.json', h.to_json)

if config['interface']
  h = { interface: config['interface'] }
  write_file('serf/interface.json', h.to_json)
end

tags = config['tags'] || {}
h = { tags: tags.merge({ role: config['role'] }) }
write_file('serf/tags.json', h.to_json)

if config['token']
  h = { rpc_auth: config['token'] }
  write_file('serf/auth.json', h.to_json, perm: 0600)
end

cluster_vars = []
cluster_vars << %(cw_CLUSTER_uuid="#{config['uuid']}")
if config['master']
  cluster_vars << %(cw_CLUSTER_master="#{config['master']}")
end
if config['name']
  cluster_vars << %(cw_CLUSTER_name="#{config['name']}")
end
if config['interface']
  cluster_vars << %(cw_CLUSTER_iface="#{config['interface']}")
end
cluster_vars << %(cw_CLUSTER_quorum="#{config['quorum'] || 1}")
cluster_vars << %(cw_CLUSTER_service_url="#{config['service_url']}")
write_file('cluster.vars.sh', cluster_vars.join("\n"))
write_file('config.rc', cluster_vars.join("\n"))

auth_vars = []
if config['token']
  auth_vars << %(cw_CLUSTER_auth_token="#{config['token']}")
end
write_file('auth.rc', auth_vars.join("\n"), perm: 0600)

instance_vars = []
instance_vars << %(cw_INSTANCE_role="#{config['role']}")
instance_vars << %(cw_INSTANCE_log="#{config['log'] || '/var/log/clusterware/instance.log'}")
tags.each do |k,v|
  instance_vars << %(cw_INSTANCE_tag_#{k.upcase.tr('-','_')}="#{v}")
end
write_file('instance.vars.sh', instance_vars.join("\n"))
write_file('instance.rc', instance_vars.join("\n"))
RUBY

    cp -p "${cw_ROOT}/etc/config/cluster/serf"/*.json "${cw_ROOT}/etc/serf"

    if [ -f "${cw_ROOT}"/etc/genders ]; then
        . "${cw_ROOT}"/etc/config/cluster/instance.rc
        if [ "${cw_INSTANCE_role}" == "master" ]; then
            short_name="$(hostname -s)"
            if ! grep -q "^${short_name}" "${cw_ROOT}"/etc/genders; then
                echo "${short_name} master,masters,cluster,all" >> "${cw_ROOT}"/etc/genders
            fi
        fi
    fi
}

setup

require ruby
require distro
require handler
require member

_JQ="${cw_ROOT}"/opt/jq/bin/jq

handler_tee main "$@"
