---
title: Alces Flight Access Manager
short_title: Access
paras:
  - >
    Your cluster has been configured with the Access Manager appliance,
    which enables you to manage and access remote login and VNC sessions
    running in the cluster.
  - >
    <a href="_APPLIANCE_URL_">Access the
    Access Manager appliance by clicking here</a>.
