#!/bin/bash
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local session sessionid

    source "${cw_ROOT}/etc/config/task/task.vars.sh"

    # If necessary, re-execute ourselves as the correct user before
    # starting the session.
    process_reexec_su $cw_TASK_RUNUSER

    session=${cw_TASK_param_SESSION-:gnome}
    sessionid=$("${cw_ROOT}"/bin/alces session start --terse $session)
    alces session wait $sessionid 1>&2
}

setup
require process
main "$@"
