#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
  local a xdg_config
  IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
  for a in "${xdg_config[@]}"; do
      if [ -e "${a}"/clusterware/config.rc ]; then
          source "${a}"/clusterware/config.rc
          break
      fi
  done
  if [ -z "${cw_ROOT}" ]; then
      echo "$0: unable to locate clusterware configuration"
      exit 1
  fi
  kernel_load
}

main() {
  eval "$(member_parse)"
  scheduler_roles=$(member_find_tag "scheduler_roles" "${cw_MEMBER_tags}")
  if [[ "${scheduler_roles}" == *":compute:"* ]]; then
    autoscaling_group=$(member_find_tag "autoscaling_group" "${cw_MEMBER_tags}")
    if [ "${autoscaling_group}" ]; then
      log "Member ${cw_MEMBER_name} leaving autoscaling group ${autoscaling_group}"

      rm "${cw_ROOT}/etc/config/autoscaling/groups/${autoscaling_group}/${cw_MEMBER_name}"

      if [ ! "$(ls -A "${cw_ROOT}/etc/config/autoscaling/groups/${autoscaling_group}/")" ]; then
        # That was the last member of the group
        # Find which group label corresponds to that group
        for label in ${cw_ROOT}/etc/config/autoscaling/by-label/*; do
          label_group=$(basename `readlink "$label"`)
          if [[ "$label_group" == "$autoscaling_group" ]]; then
            autoscaling_group_label="$(basename "$label")"

            # Delete the label associated with this group
            rm "$label"
            break
          fi
        done

        if [[ "$autoscaling_group_label" != "" ]]; then  # If it _is_ empty something went wrong somewhere...
          log "Triggering local 'autoscaling-prune-group' event with: ${autoscaling_group_label}"
          "${cw_ROOT}"/libexec/share/trigger-event --local autoscaling-prune-group "${autoscaling_group_label}"
        fi

        # And finally remove the group from our config
        rmdir "${cw_ROOT}/etc/config/autoscaling/groups/${autoscaling_group}"
      fi
    fi
  fi
}

setup
require handler
require files
require log
require member

log_set_default "/var/log/clusterware/autoscaler.log"

handler_tee main "$@"
