#!/bin/bash

# Create .byslot.q and .byhost.q queues for a given queuename, drawing from a
# given hostgroup.

. /etc/profile.d/alces-clusterware.sh
. /etc/xdg/clusterware/config.vars.sh
module purge
module use "${cw_ROOT}"/etc/modules
module load services/gridscheduler

_lock() {
    mkdir -p "${cw_ROOT}"/var/lock
    exec 9> "${cw_ROOT}"/var/lock/cluster-sge.lock && flock -w30 9
}

_unlock() {
    exec 9>&-
}

if [ -f "${cw_ROOT}/etc/cluster-sge.rc" ]; then
    . "${cw_ROOT}/etc/cluster-sge.rc"
fi

if _lock; then
  queuename="$1"
  hostgroup="$2"

  if ! qconf -sq "${queuename}" > /dev/null 2>&1; then
    echo "Creating new queue $queuename"
    tmpfile="$(mktemp /tmp/sge-add-queue.XXXXXXXX)"

    qconf -sq "byslot.q" | \
      sed -e "s/qname.*/qname ${queuename}.byslot.q" \
          -e "s/hostlist.*/hostlist @${hostgroup}"
      > "$tmpfile"

    qconf -Aq "$tmpfile"

    qconf -sq "bynode.q" | \
      sed -e "s/qname.*/qname ${queuename}.bynode.q" \
          -e "s/hostlist.*/hostlist @${hostgroup}"
      > "$tmpfile"

    qconf -Aq "$tmpfile"

    rm -f "${tmpfile}"
  fi
else
    echo "Locking failed; unable to add queue"
fi
