#!/bin/bash

. /etc/profile.d/alces-clusterware.sh
. /etc/xdg/clusterware/config.vars.sh
module purge
module use "${cw_ROOT}"/etc/modules
module load services/gridscheduler

if [ -f "${cw_ROOT}/etc/cluster-sge.rc" ]; then
    . "${cw_ROOT}/etc/cluster-sge.rc"
fi
cw_CLUSTER_SGE_max_rt_seconds=${cw_CLUSTER_SGE_max_rt_seconds:-259200}
cw_CLUSTER_SGE_min_vmem_gb=${cw_CLUSTER_SGE_min_vmem_gb:-4}

name="$1"
domainname="$(hostname -d)"
if [[ "${name}" != *"."* ]]; then
    # name is simply "<hostname>"
    short_name="${name}"
    name="${name}.${domainname}"
else
    if [[ "${name}" != *".${domainname}" ]]; then
        # name is "<hostname>.<subdomain>"
        name="$1.${domainname}"
    fi
    short_name=$(echo ${name} | cut -f1 -d'.')
fi
ip="$2"
slots="${3:-1}"
vmem="$4"

if [ ${vmem:-0} -lt $cw_CLUSTER_SGE_min_vmem_gb ]; then
    vmem=$cw_CLUSTER_SGE_min_vmem_gb
fi

tmpfile="$(mktemp /tmp/sge-add-node.XXXXXXXX)"

if ! grep -q "${ip}.*${name}" /etc/hosts; then
    # no applicable entry yet.
    if grep -q "${ip}" /etc/hosts; then
        # IP present, but not this name: sed
        sed -e "s/${ip} \(.*\)/${ip} ${name} ${short_name} \1/g" -i /etc/hosts
    elif grep -q "${name}" /etc/hosts; then
        # name present, but not this IP: sed out the existing name
        sed -re "s/(.*)\s${name}( .*|$)/\1 \2/g" /etc/hosts | \
            sed -re "s/(.*)\s${short_name}( .*|$)/\1 \2/g" | \
            egrep -v "^(\S+)\s*$" > "${tmpfile}"
        cat "${tmpfile}" > /etc/hosts
        echo "${ip} ${name} ${short_name}" >> /etc/hosts
    else
        # IP and name not present, just add
        echo "${ip} ${name} ${short_name}" >> /etc/hosts
    fi
fi

cat << EOF > "${tmpfile}"
hostname              $name
load_scaling          NONE
complex_values        slots=$slots,exclusive=true,h_vmem=${vmem}G,h_rt=${cw_CLUSTER_SGE_max_rt_seconds}
user_lists            NONE
xuser_lists           NONE
projects              NONE
xprojects             NONE
usage_scaling         NONE
report_variables      NONE
EOF
qconf -Ae "${tmpfile}" || qconf -Me "${tmpfile}"

set -o pipefail
# Add to allhosts group
if ! qconf -shgrp @allhosts | grep -q "${name}"; then
    qconf -shgrp @allhosts | sed -e "s/^hostlist NONE/hostlist /g" \
        -e "s/^hostlist \(.*\)/hostlist ${name} \1/g" > "${tmpfile}" && \
        qconf -Mhgrp "${tmpfile}"
fi
if [ $slots -gt 1 ]; then
    # Add to slot-aware hostgroup
    if ! qconf -shgrp @${slots}slot | grep -q "${name}"; then
        qconf -shgrp @${slots}slot | sed -e "s/^hostlist NONE/hostlist /g" \
            -e "s/^hostlist \(.*\)/hostlist ${name} \1/g" > "${tmpfile}" && \
            qconf -Mhgrp "${tmpfile}"
        # Workaround to make qmaster pay attention to hostgroup slots
        qconf -sq byslot.q > "${tmpfile}" && \
            qconf -Mq "${tmpfile}"
    fi
fi
set +o pipefail
rm -f "${tmpfile}"

if [ -f "${cw_ROOT}"/etc/genders ]; then
    if ! grep -q "^${short_name}" "${cw_ROOT}"/etc/genders; then
        echo "${short_name} nodes,compute,cluster,slave,all" >> "${cw_ROOT}"/etc/genders
    fi
fi
