#!/bin/bash

module purge
module load services/gridscheduler

name="$1"
ip="$2"
slots="$3"
vmem="$4"

if ! grep -q "${ip}.*${name}" /etc/hosts; then
    # no applicable entry yet.
    if grep -q "${ip}" /etc/hosts; then
        # IP present, but not this name: sed
        sed -e "s/\(${ip}.*\)/\1 ${name}/g" -i /etc/hosts
    elif grep -q "${name}" /etc/hosts; then
        # name present, but not this IP: sed out the existing name
        sed -e "s/\(.*\)${name}\(.*\)/\1\2/g" -i /etc/hosts
        echo "${ip} ${name}" >> /etc/hosts
    else
        # IP and name not present, just add
        echo "${ip} ${name}" >> /etc/hosts
    fi
fi

tmpfile="$(mktemp /tmp/sge-add-node.XXXXXXXX)"

cat << EOF > "${tmpfile}"
hostname              $name
load_scaling          NONE
complex_values        slots=$slots,exclusive=true,h_vmem=${vmem}G
user_lists            NONE
xuser_lists           NONE
projects              NONE
xprojects             NONE
usage_scaling         NONE
report_variables      NONE
EOF
qconf -Ae "${tmpfile}" || qconf -Me "${tmpfile}"

for i in $(qconf -shgrpl)
   qconf -shgrp $i | sed -e "s/^hostlist NONE/hostlist /g" \
       -e "s/^hostlist \(.*\)/hostlist foo \1/g"
   qconf -Mhgrp "${tmpfile}"
done
rm -f "${tmpfile}"

if [ -f "${cw_ROOT}"/etc/genders ]; then
    echo "${name} nodes,compute,cluster,slave,all" >> "${cw_ROOT}"/etc/genders
fi
