#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2015-2016 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local tags tag tuple key value vmem_gb slots hook_dir intf master_ip scheduler_roles instanceid group
    files_load_config instance config/cluster

    eval "$(member_parse)"
    log "Member data parsed: ${cw_MEMBER_name} (${cw_MEMBER_ip}) -- ${cw_MEMBER_tags}" "${cw_CLUSTER_SGE_log}"

    if [[ "${cw_INSTANCE_tag_SCHEDULER_ROLES}" == *":master:"* ]]; then
        log "This instance is a scheduler master; checking new member for scheduler compute role" \
            "${cw_CLUSTER_SGE_log}"
        IFS=',' read -a tags <<< "${cw_MEMBER_tags}"
        for tag in "${tags[@]}"; do
            IFS='=' read -a tuple <<< "${tag}"
            log "Found tuple: ${tag}, key: ${tuple[0]}, value: ${tuple[1]}" "${cw_CLUSTER_SGE_log}"
            key=${tuple[0]}
            value=${tuple[1]}
            if [ "$key" == "scheduler_roles" ]; then
                scheduler_roles="${value}"
            elif [ "$key" == "ram_gb" ]; then
                vmem_gb="${value}"
            elif [ "$key" == "slots" ]; then
                slots="${value}"
            elif [ "$key" == "aws_instanceid" ]; then
                instanceid="${value}"
            elif [ "$key" == "aws_group" ]; then
                group="${value}"
            fi
        done
        if [[ "${scheduler_roles}" == *":compute:"* || "${scheduler_roles}" == *":submit:"* ]]; then
            hook_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
            # Wait for a short while to ensure that the addition of
            # the name to /etc/hosts percolates through to SGEs name
            # resolution routines.
            sleep 2

            if [[ "${scheduler_roles}" == *":compute:"* ]]; then
                log "Adding node: ${cw_MEMBER_name} (${cw_MEMBER_ip}) with slots=${slots} and vmem=${vmem_gb}G" \
                    "${cw_CLUSTER_SGE_log}"
                ${hook_dir}/share/sge-add-node "${cw_MEMBER_name}" "${cw_MEMBER_ip}" "${slots}" "${vmem_gb}" 2>&1 | log_blob "${cw_CLUSTER_SGE_log}" "sge-add-node"
            else
                log "Adding node: ${cw_MEMBER_name} (${cw_MEMBER_ip}) as submit host" \
                    "${cw_CLUSTER_SGE_log}"
                ${hook_dir}/share/sge-add-submit-host "${cw_MEMBER_name}" 2>&1 | \
                    log_blob "${cw_CLUSTER_SGE_log}" "sge-add-node"
            fi

            intf="$(network_get_route_iface ${cw_MEMBER_ip})"
            master_ip="$(network_get_network_address ${cw_MEMBER_ip})"

            handler_iptables_insert INPUT -i ${intf} -s ${cw_MEMBER_ip} -p tcp --dport 6444 -j ACCEPT | \
                log_blob "${cw_CLUSTER_SGE_log}"

            log "Broadcasting 'sge-ready' event with: ${master_ip} $(hostname -f) ${cw_MEMBER_ip}" \
                "${cw_CLUSTER_SGE_log}"
            handler_broadcast sge-ready ${master_ip} $(hostname -f) ${cw_MEMBER_ip}
        else
            log "New member does not have scheduler roles; no further processing required" \
                "${cw_CLUSTER_SGE_log}"
        fi
    fi
}

setup
require member
require network
require handler
require log
require files

if files_load_config --optional cluster-sge; then
    handler_tee main "$@"
fi
