#!/bin/bash
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local tags tag tuple key value vmem_gb slots hook_dir intf master_ip scheduler_roles
    . "${cw_ROOT}"/etc/config/cluster/instance.rc

    eval "$(member_parse)"
    log "Member data parsed: ${cw_MEMBER_name} (${cw_MEMBER_ip}) -- ${cw_MEMBER_tags}" "${cw_CLUSTER_SGE_log}"
    "${cw_ROOT}"/libexec/share/update-etc-hosts "${cw_MEMBER_name}" "${cw_MEMBER_ip}"

    if [[ "${cw_INSTANCE_tag_SCHEDULER_ROLES}" == *":master:"* ]]; then
	log "This instance is a scheduler master; checking new member for scheduler compute role" \
	    "${cw_CLUSTER_SGE_log}"
        IFS=',' read -a tags <<< "${cw_MEMBER_tags}"
        for tag in "${tags[@]}"; do
            IFS='=' read -a tuple <<< "${tag}"
            log "Found tuple: ${tag}, key: ${tuple[0]}, value: ${tuple[1]}" "${cw_CLUSTER_SGE_log}"
            key=${tuple[0]}
            value=${tuple[1]}
            if [ "$key" == "scheduler_roles" ]; then
                scheduler_roles="${value}"
            elif [ "$key" == "ram_gb" ]; then
                vmem_gb="${value}"
            elif [ "$key" == "slots" ]; then
                slots="${value}"
            fi
        done
        if [[ "${scheduler_roles}" == *":compute:"* ]]; then
            log "Adding node: ${cw_MEMBER_name} (${cw_MEMBER_ip}) with slots=${slots} and vmem=${vmem_gb}G" \
                "${cw_CLUSTER_SGE_log}"
            hook_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
            ${hook_dir}/share/sge-add-node "${cw_MEMBER_name}" "${cw_MEMBER_ip}" "${slots}" "${vmem_gb}" 2>&1 | log_blob "${cw_CLUSTER_SGE_log}" "sge-add-node"

            intf="$(network_get_route_iface ${cw_MEMBER_ip})"
            master_ip="$(network_get_network_address ${cw_MEMBER_ip})"

            if ! iptables -C INPUT -i ${intf} -s ${cw_MEMBER_ip} -p tcp --dport 6444 -j ACCEPT &>/dev/null; then
                log "Adding iptables rule: -I INPUT -i ${intf} -s ${cw_MEMBER_ip} -p tcp --dport 6444 -j ACCEPT" \
                    "${cw_CLUSTER_SGE_log}"
                iptables -I INPUT -i ${intf} -s ${cw_MEMBER_ip} -p tcp --dport 6444 -j ACCEPT
            else
                log "iptables rule already exists: -I INPUT -i ${intf} -s ${cw_MEMBER_ip} -p tcp --dport 6444 -j ACCEPT" \
                    "${cw_CLUSTER_SGE_log}"
            fi

            log "Broadcasting 'sge-ready' event with: ${master_ip} $(hostname -f) ${cw_MEMBER_ip}" \
                "${cw_CLUSTER_SGE_log}"
            handler_broadcast sge-ready ${master_ip} $(hostname -f) ${cw_MEMBER_ip}
	else
	    log "New member does not have scheduler compute role; no further processing required" \
		"${cw_CLUSTER_SGE_log}"
        fi
    fi
}

setup
require member
require network
require handler
require log

if [ -f "${cw_ROOT}/etc/cluster-sge.rc" ]; then
    . "${cw_ROOT}/etc/cluster-sge.rc"
    handler_tee main "$@"
fi
