#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require handler
require process
require network

main() {
  local type profile_name
  type=${1%%/*}
  profile_name=${1##*/}
  echo "Type: $type"
  echo "Profile: $profile_name"
}

if [ -d "${cw_ROOT}"/etc/handlers/cluster-customizer/share ]; then
    handler_add_libdir "${cw_ROOT}"/etc/handlers/cluster-customizer/share
    require customize

    if network_has_metadata_service 1; then
        files_load_config cluster-customizer
        cw_CLUSTER_CUSTOMIZER_path="${cw_CLUSTER_CUSTOMIZER_path:-${cw_ROOT}/var/lib/customizer}"
        cw_CLUSTER_CUSTOMIZER_profiles="${cw_CLUSTER_CUSTOMIZER_profiles:-default}"

        process_reexec_sudo "$@"

        main "$@"
    else
        action_die 'unable to apply: no cloud metadata service detected'
    fi
else
    action_die 'cluster-customizer handler is not enabled'
fi
