#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.rc ]; then
            source "${a}"/clusterware/config.rc
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    job_queue_process_queues "$@"
}

setup
require handler
handler_add_libdir "${cw_ROOT}"/etc/handlers/cluster-job-queue/share
require job-queue

handler_tee main "$@"
