#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

_notify_storage_appliance() {
    local port address appliance_type
    port="$1"
    address="$2"
    appliance_type="storage"
    files_load_config config config/cluster

    ruby_run <<RUBY
require 'yaml'
require 'base64'

    config_file = '/opt/alces-storage-manager/webapp/config/storagemanager.yml'
    config = YAML.load_file(config_file)

    config['collections'] ||= {}

    hash = Base64.strict_encode64("${address}:${port}")

    config['collections'][hash] = {
        "name": "${cw_CLUSTER_name}",
        "ip": "${address}",
        "auth_port": ${port},
        "ssl": true,
    }

    File.write(config_file, YAML.dump(config))

RUBY
}

_add_storage_master_node() {
    local addr port
    addr="$1"
    port="$2"
    files_load_config --optional cluster-appliances
    cw_APPLIANCES_storage_MANAGER_ROOT="${cw_APPLIANCES_storage_MANAGER_ROOT:-/opt/alces-storage-manager}"
    if [ -f "${cw_ROOT}"/etc/config/cluster-appliances/storage-endpoints.yml ]; then
	echo "Cowardly refusing to reconfigure existing Alces Storage Manager"
    else
	mkdir -p "${cw_APPLIANCES_storage_MANAGER_ROOT}"/webapp/config
	cat <<EOF > "${cw_ROOT}"/etc/config/cluster-appliances/storage-endpoints.yml
---
:endpoints:
- "${addr}:${port}"
EOF
        _notify_storage_appliance "${port}" "${addr}"
    fi
}

_add_access_master_node() {
    local addr port
    addr="$1"
    port="$2"
    files_load_config --optional cluster-appliances
    cw_APPLIANCES_access_MANAGER_ROOT="${cw_APPLIANCES_access_MANAGER_ROOT:-/opt/alces-access-manager}"
    if [ -f "${cw_ROOT}"/etc/config/cluster-appliances/access-endpoints.yml ]; then
	echo "Cowardly refusing to reconfigure existing Alces Access Manager"
    else
	cat <<EOF > "${cw_ROOT}"/etc/config/cluster-appliances/access-endpoints.yml
---
:endpoints:
- "${addr}:${port}"
EOF
	files_load_config config config/cluster
        sed -e 's/^clusters: \[\]$/clusters:/g' \
	    -e "s/^clusters:$/clusters:\n  - name: ${cw_CLUSTER_name}\n    ip: ${addr}\n    auth_port: ${port}\n    ssl: true\n/g" \
	    -i "${cw_APPLIANCES_access_MANAGER_ROOT}"/webapp/config.yaml
    fi
}

main() {
    local tags tag tuple key value storage_roles storage_daemon_port access_roles access_daemon_port

    files_load_config instance config/cluster

    if [[ "${cw_INSTANCE_role}" == "appliance" ]]; then
        eval "$(member_parse)"
        echo "Tags for member ${cw_MEMBER_name} (${cw_MEMBER_ip}): ${cw_MEMBER_tags}"
        IFS=',' read -a tags <<< "${cw_MEMBER_tags}"
        for tag in "${tags[@]}"; do
            IFS='=' read -a tuple <<< "${tag}"
            echo "Found tuple: ${tag}, key: ${tuple[0]}, value: ${tuple[1]}"
            key=${tuple[0]}
            value=${tuple[1]}
            if [ "$key" == "storage_roles" ]; then
                storage_roles="${value}"
            elif [ "$key" == "storage_daemon_port" ]; then
                storage_daemon_port="${value}"
            elif [ "$key" == "access_roles" ]; then
                access_roles="${value}"
            elif [ "$key" == "access_daemon_port" ]; then
                access_daemon_port="${value}"
            fi
        done
        if [[ "${cw_INSTANCE_tag_APPLIANCE_ROLES}" == *":storage:"* && "${storage_roles}" == *":master:"* ]]; then
            echo "Adding Storage Manager master node: ${cw_MEMBER_name} (${cw_MEMBER_ip}:${storage_daemon_port:-25268})"
            _add_storage_master_node "${cw_MEMBER_ip}" "${storage_daemon_port:-25268}"
        fi
        if [[ "${cw_INSTANCE_tag_APPLIANCE_ROLES}" == *":access:"* && "${access_roles}" == *":master:"* ]]; then
            echo "Adding Access Manager master node: ${cw_MEMBER_name} (${cw_MEMBER_ip}:${access_daemon_port:-25269})"
            _add_access_master_node "${cw_MEMBER_ip}" "${access_daemon_port:-25269}"
        fi
    fi
}

setup
require member
require handler
require files
require distro

handler_tee main "$@"
