#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2015-2016 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local port
    files_load_config instance config/cluster
    port="${cw_INSTANCE_tag_STORAGE_DAEMON_PORT:-25268}"
    if [[ "${cw_INSTANCE_tag_STORAGE_ROLES}" == "*:master:*" ]]; then	
        if ! iptables -C INPUT -p tcp --dport ${port} -j ACCEPT &>/dev/null; then
            echo "Adding iptables rule: -I INPUT -p tcp --dport ${port} -j ACCEPT"
            iptables -I INPUT -p tcp --dport ${port} -j ACCEPT
        else
            echo "iptables rule already exists: -I INPUT -p tcp --dport ${port} -j ACCEPT"
        fi
        if distro_start_service clusterware-alces-storage-manager-daemon; then
            echo "Alces Storage Manager Daemon service started"
        else
            echo "Unable to start Alces Storage Manager Daemon service"
        fi
    fi
}

setup
require distro
require handler
require files

handler_tee main "$@"
